### PR TITLE
Changes in README.md for Mac/Linux Users.

### PR DESCRIPTION
**Pull request by aman-3003**

### CODE REVIEW

**Review by SRvSaha — APPROVED** [review]

**Comment by SRvSaha** [comment]
@aman-3003 Please also add the steps of going to Security and Allowing App from Unidentified Developers to run in Mac. That's a thing users have to do.

**Comment by aman-3003** [comment]
> @aman-3003 Please also add the steps of going to Security and Allowing App from Unidentified Developers to run in Mac. That's a thing users have to do.

There is no need to do that it didn't ask me when i first ran it. And i have tried it on another user and this doesn't need these steps.

**Comment by SRvSaha** [comment]
> 
> 
> > @aman-3003 Please also add the steps of going to Security and Allowing App from Unidentified Developers to run in Mac. That's a thing users have to do.
> 
> There is no need to do that it didn't ask me when i first ran it. And i have tried it on another user and this doesn't need these steps.

Actually it was asking me everytime I was trying. In Security -> Privacy, there is an option of Allow Only App Store and Allow Identified Developers as well. Probably it is by default turned on for you. And for new Mac Users, it might not be turned on. Just check that part. Rest the ReadMe is okay. Also, I'd suggest to move this to the Part "For Folk who want to get shit done". Make 3 section for Windows and then Mac/Linux. That'd be easier for users to follow. Don't remove the Header  "For Folk who want to get shit done"

**Comment by aman-3003** [comment]
> > > @aman-3003 Please also add the steps of going to Security and Allowing App from Unidentified Developers to run in Mac. That's a thing users have to do.
> > 
> > 
> > There is no need to do that it didn't ask me when i first ran it. And i have tried it on another user and this doesn't need these steps.
> 
> Actually it was asking me everytime I was trying. In Security -> Privacy, there is an option of Allow Only App Store and Allow Identified Developers as well. Probably it is by default turned on for you. And for new Mac Users, it might not be turned on. Just check that part. Rest the ReadMe is okay. Also, I'd suggest to move this to the Part "For Folk who want to get shit done". Make 3 section for Windows and then Mac/Linux. That'd be easier for users to follow. Don't remove the Header "For Folk who want to get shit done"

Okay will check that and make another pull request.

**Pull request merged**
