### PR TITLE
District Codes

### PR DESCRIPTION
**Pull request by AkulRastogi**
Added a markdown file for District Codes - sorted in alphabetical order by State and District Names.

### CODE REVIEW

**Comment by AkulRastogi** [comment]
#8 Fix

**Comment by SRvSaha** [comment]
Hi @AkulRastogi, thanks for your effort on creating the markdown. Appreciate it.
However, I feel that since DistrictName and District Code are Key-Value Pairs in our Config file, so it would be better in terms of UX and User Friendliness if you can create the same in JSON Format file. 

Say for example:

Currently you are doing this: 

State | DistrictName | DistrictCode
--- | --- | ---
Andaman and Nicobar Islands | Nicobar | 3
Andaman and Nicobar Islands | North and Middle Andaman | 1
Andaman and Nicobar Islands | South Andaman | 2
Andhra Pradesh | Anantapur | 9
Andhra Pradesh | Chittoor | 10

This is what you can do: 

1. Create a JSON inside the /data directory with the name State_District_DistrictCode_Mapping.json
2. Inside the JSON file, there will be mapping like ```javascript {
  "Andaman and Nicobar Islands": {
    "Nicobar" : 3,
    "North and Middle Andaman" : 1,
    "South Andaman" : 2
  },
  "Andhra Pradesh" : {
    "Anantapur" : 9,
    "Chittoor" : 10
  }
}```

In this way, it will be very easy for the users of the application to copy-paste the value in the config file.
Just make this fixes and update the README to mention how to get the district details and I'll be happy to merge your PR : 
>"Districts": 
 {
    // "DistrictName": DistrictCode
    "<REPLACE_ME_KEY>" : "<REPLACE_ME_VALUE>" 
 } // You'll get the District Name and District Codes `from CoWIN's website`, as of now things are done for Mumbai and nearby districts. Example, Replace <REPLACE_ME_KEY> WITH "Mumbai" and <REPLACE_ME_VALUE> WITH 395. Keep adding more, if you need for more districts.

Instead of COWIN's website, it will be path to the new resource file.
I think it's better if you keep these in the resources folder inside data/

**Comment by SRvSaha** [comment]
@AkulRastogi Meanwhile, don't delete the DistrictCodes.md that you created. It'll be better while someone searches or views it. So, shall merge with 2 commits with 2 different file formats, one Markdown for better readability and another JSON of better UX.

**Review by SRvSaha — CHANGES_REQUESTED** [review]
<html><body>
<p>Hi <a class="user-mention" data-hovercard-type="user" data-hovercard-url="/users/AkulRastogi/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/AkulRastogi">@AkulRastogi</a>, thanks for your effort on creating the markdown. Appreciate it.<br>
However, I feel that since DistrictName and District Code are Key-Value 
Pairs in our Config file, so it would be better in terms of UX and User 
Friendliness if you can create the same in JSON Format file.</p>
<p>Say for example:</p>
<p>Currently you are doing this:</p>


State | DistrictName | DistrictCode
-- | -- | --
Andaman and Nicobar Islands | Nicobar | 3
Andaman and Nicobar Islands | North and Middle Andaman | 1
Andaman and Nicobar Islands | South Andaman | 2
Andhra Pradesh | Anantapur | 9
Andhra Pradesh | Chittoor | 10


<p>This is what you can do:</p>
<ol>
<li>Create a JSON inside the /data directory with the name State_District_DistrictCode_Mapping.json</li>
<li>Inside the JSON file, there will be mapping like <code>javascript { 
  "Andaman and Nicobar Islands": { "Nicobar" : 3, "North and Middle 
Andaman" : 1, "South Andaman" : 2   },   "Andhra Pradesh" : { 
"Anantapur" : 9, "Chittoor" : 10   } }</code></li>
</ol>
<p>In this way, it will be very easy for the users of the application to copy-paste the value in the config file.<br>
Just make this fixes and update the README to mention how to get the district details and I'll be happy to merge your PR :</p>
<blockquote>
<p>"Districts":<br>
{<br>
// "DistrictName": DistrictCode<br>
"&lt;REPLACE_ME_KEY&gt;" : "&lt;REPLACE_ME_VALUE&gt;"<br>
} // You'll get the District Name and District Codes <code>from CoWIN's website</code>,
 as of now things are done for Mumbai and nearby districts. Example, 
Replace &lt;REPLACE_ME_KEY&gt; WITH "Mumbai" and 
&lt;REPLACE_ME_VALUE&gt; WITH 395. Keep adding more, if you need for 
more districts.</p>
</blockquote>
<p>Instead of COWIN's website, it will be path to the new resource file.<br>
I think it's better if you keep these in the resources folder inside data/</p>
</body>
</html>

**Review by SRvSaha — COMMENTED** [review]
@AkulRastogi Meanwhile, don't delete the DistrictCodes.md that you created. It'll be better while someone searches or views it. So, shall merge with 2 commits with 2 different file formats, one Markdown for better readability and another JSON of better UX.

**Review by AkulRastogi — COMMENTED** [review]
Added JSON file and Updated README with the relative link to json file

**Review by SRvSaha — CHANGES_REQUESTED** [review]
Looks good to me.
Just a couple of things and we are reach to merge:

1. Keep the FileName Verbose so that it is easily understood like "State_District_DistrictCode_Mapping".json/md
2. Move the file to /resources directory inside /data. So it'll be like data/resources/{FILENAME}
3. In README, don't add a link below, add it inline.

**Comment by AkulRastogi** [comment]
@SRvSaha I am not sure if we can add inline link inside a code block without loosing the code highlighting. Let me know if this is possible.

**Review by SRvSaha — APPROVED** [review]
Looks good to me! 
Thanks for you contribution @AkulRastogi,merging the code!

**Pull request merged**
