### PR TITLE
Auto otp readme

### PR DESCRIPTION
**Pull request by deepak-batra**
Added the Telegram and IFTTT things in readme.

### CODE REVIEW

**Comment by deepak-batra** [comment]
@SRvSaha Added the auto-otp instructions in readme.

**Comment by SRvSaha** [comment]
Hi @deepak-batra, thanks a lot for the contribution. I will go through it, just one thing, can the setup be a bit easier for end users. Now there are lots of steps to be done, can we automate some them.

Also, another thing is, from IFTTT, is it possible to send customized message to Telegram like SMS_TEXT = "USER_MOBILE_NO:OTP"

If this is possible, we can post the messages in a Centralized Channel and user doesn't have to worry about most of the Telegram related setup.

Never used IFTTT, so need your help. Also, yeah if possible share the APIs used for Async Read. That'll help in searching for .NET Equivalent API in the SDK.

Good work, appreciate it

**Review by SRvSaha — COMMENTED** [review]
Looks good to me, just one thing.
Is there any possible way to lessen the setup work for End Users?

**Comment by SRvSaha** [comment]
@deepak-batra Another doubt that I have is, how do we integrate the same with iOS? I could not see any option of iOS SMS Reading.
I saw somewhere that people use Shortcuts App inside iOS for the purpose, can you please check whether it is possible to integrate iOS with Telegram so that similar approach we are taking with IFTTT can be done for Shortcuts App as well

**Comment by deepak-batra** [comment]
> Hi @deepak-batra, thanks a lot for the contribution. I will go through it, just one thing, can the setup be a bit easier for end users. Now there are lots of steps to be done, can we automate some them.
> 
I agree with the number of steps. I took the inspiration from the automation [here]( https://github.com/bombardier-gif/covid-vaccine-booking#option-1-ifttt) and twisted around because of privacy concerns. 
> Also, another thing is, from IFTTT, is it possible to send customized message to Telegram like SMS_TEXT = "USER_MOBILE_NO:OTP"
> 
This will be a major privacy issue, since the phone number and otp the only thing needed to access beneficiary details. Rather than a public channel, it can be a group as well with the IFTTT bot as a member. 
> If this is possible, we can post the messages in a Centralized Channel and user doesn't have to worry about most of the Telegram related setup.
> 
> Never used IFTTT, so need your help. Also, yeah if possible share the APIs used for Async Read. That'll help in searching for .NET Equivalent API in the SDK.
> 
I'll add the APIs here by the night. 
> Good work, appreciate it

**Comment by SRvSaha** [comment]
@deepak-batra Alright, thanks. Let's keep the R&D Work. I am planning to deploy v4.2.0 by weekend, so we have a couple of days to see if anything else would be possible which is simpler. Else we'll go ahead with this! What say?

**Comment by deepak-batra** [comment]
@SRvSaha Sorry, but I forgot another caveat of telegram, user would need to get their api_key & api_hash from telegram.com which is another hassle. I think the email suggestion by @debansur earlier would be better. This would decentralise the design and everyone can handle their own thing. [This](https://pythonprogramminglanguage.com/read-gmail-using-python/) talks about reading gmail in python and [this](https://ifttt.com/applets/BU7rehgp-receive-otp-as-email) talks about sending OTP as an sms to an email. That would be straight-forward and won't require the cumbersome telegram setup.

User can keep their email and password in the appsettings.json and there won't be any leakage. LMK and I'll update the PR.

**Comment by SRvSaha** [comment]
@deepak-batra Yeah sounds good, shall think over it and then we can discuss.

**Comment by SRvSaha** [comment]
@deepak-batra Hi, due to throttling of IP that started yesterday, there has been some issues. Do you feel Auto OTP will be helpful even now? As IPs are gererally getting throttled after say 100 requests/5 min (data not sure)

**Comment by deepak-batra** [comment]
Hey, I don't have a strong opinion on this. I'm okay to drop this off as well.

**Comment by SRvSaha** [comment]
> 
> 
> @SRvSaha Hey, I don't have a strong opinion on this. I'm okay to drop this off as well.

Hi, we won't be dropping this, since you already have done a great job! We'll launch it in the next major release v5.0.0

**Comment by SRvSaha** [comment]
Closing, Reason #68

**Pull request closed without merging**
